### ISSUE TITLE
Demise css classes in App.css and use tailwind classes directly

### ISSUE THREAD

**Issue by subramanian-elavathur** [adtyavrdhn/Soring-Visualizer-React-#1]
```css
.tower {
  width: 0.7%;
}

.TowerContainer {
  display: flex;
  gap: 0.4rem;
  margin-top: 15px;
}

.towers-grid {
  width: 100%;
}
```
